mces/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('estimator/', include('estimator.urls')),
    path('trends/', include('trends.urls')),
    path('report/', include('report.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trends/urls.py
from django.conf.urls import re_path

from . import views

app_name = 'trends'

urlpatterns = [
    re_path(r'^trend/$', views.TrendView.as_view(), name='yield-rate-maintenance-chart'),

    # AJAX URLs
    re_path(r'^ajax/get-machine-trends/$', views.get_machine_trends_and_maintenance,
            name='get-machine-trends-and-maintenance'),
    re_path(r'^ajax/machine-autocomplete/$', views.machine_autocomplete, name='machine-autocomplete'),
]

trends/models.py
from django.db import models

# Create your models here.

trends/forms.py
from django import forms
from bootstrap_datepicker_plus import DatePickerInput


class TrendForm(forms.Form):

    REPORT_TYPE_CHOICES = (
        ('Cell', 'Cell-based'),
        ('Panel', 'Panel-based')
    )

    start_date = forms.DateField(
        widget=DatePickerInput(
            attrs={
                "autocomplete": "off"  # disable input history
            },
            options={
                "format": "YYYY-MM-DD",
                "minDate": "2018-01-01",  # PROJECT START DATE
                "useCurrent": False,
                "showClose": False,
                "showClear": False,
                "showTodayButton": False,
            }
        ),
        required=True
    )

    end_date = forms.DateField(
        widget=DatePickerInput(
            attrs={
                "autocomplete": "off"  # disable input history
            },
            options={
                "format": "YYYY-MM-DD",
                "useCurrent": False,
                "showClose": False,
                "showClear": False,
                "showTodayButton": False,
            }
        ),
        required=True
    )

    machine = forms.CharField(
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "autocomplete": "off"  # disable input history
        }),
        max_length=6
    )

    report_type = forms.ChoiceField(
        choices=REPORT_TYPE_CHOICES,
        widget=forms.Select(),
        required=True
    )

trends/views.py
from django.shortcuts import render
from django.views.generic import View
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.db.models import Min

from .forms import *

from estimator.models import Machine_Yield_Rate_History, Maintenance_History

import datetime
import json


class TrendView(View):
    def get(self, request):
        form = TrendForm()
        return render(request, 'trends/trends-chart.html', {'form': form})


@csrf_exempt
def get_machine_trends_and_maintenance(request):
    if request.is_ajax():
        # Get data sent using ajax
        start_date_str = request.GET.get('start_date', None)
        end_date_str = request.GET.get('end_date', None)
        machine = request.GET.get('machine', None)
        report_type = request.GET.get('report_type', None)

        # Convert str to datetime object
        date_format = '%Y-%m-%d'
        start_date = datetime.datetime.strptime(start_date_str, date_format)
        end_date = datetime.datetime.strptime(end_date_str, date_format)

        # Query yield rate based on the input parameters
        machine_yield_rates = Machine_Yield_Rate_History.objects \
            .values('period', 'yield_rate') \
            .filter(machine=machine, start_period__range=(start_date, end_date), end_period__range=(start_date, end_date), analyze_type=report_type) \
            .order_by('end_period')

        # Get min yield rate
        min_yield_rate = Machine_Yield_Rate_History.objects.values_list('yield_rate')\
            .filter(machine=machine,
                    start_period__range=(start_date, end_date),
                    end_period__range=(start_date, end_date),
                    analyze_type=report_type)\
            .aggregate(Min('yield_rate'))

        # Query maintenance data period based on the input parameters
        machine_maintenance = Maintenance_History.objects \
            .values('check_in_time') \
            .filter(machine=machine, check_in_time__range=(start_date, end_date)) \
            .order_by('check_in_time')

        # Split period into two (start and end period)
        period_date_dict = {}
        date_format = '%Y%m%d'
        for index, item in enumerate(machine_yield_rates):
            period = item['period'].split('_')
            period_date_dict[index] = {}
            period_date_dict[index]['start_period'] = datetime.datetime.strptime(period[0], date_format).date()
            period_date_dict[index]['end_period'] = datetime.datetime.strptime(period[1], date_format).date()

        # Calculate machine maintenance occurrences in between the start and end periods
        maintenance_occurrence_dict = {}
        occurrence_counter = 0
        loop_counter = 0
        for key, value in period_date_dict.items():
            for item in list(machine_maintenance):
                if item['check_in_time'].date() >= value['start_period'] and item['check_in_time'].date() <= value['end_period']:
                    occurrence_counter = occurrence_counter + 1
            maintenance_occurrence_dict[loop_counter] = {}
            maintenance_occurrence_dict[loop_counter]['period'] = value['start_period'].strftime(date_format) + "_" + \
                                                                  value['end_period'].strftime(date_format)
            maintenance_occurrence_dict[loop_counter]['occurrence'] = occurrence_counter
            occurrence_counter = 0
            loop_counter += loop_counter + 1

        # Parse all the results into json form
        result = json.dumps({
            'yield_rate': list(machine_yield_rates),
            'min_yield_rate': min_yield_rate['yield_rate__min'] - 0.01,
            'maintenance_history': maintenance_occurrence_dict,
        })

        return JsonResponse(result, content_type='application/json', safe=False)


@csrf_exempt
def machine_autocomplete(request):
    if request.is_ajax():
        machine = request.GET.get('search', None)
        queryset = Machine_Yield_Rate_History.objects.filter(machine__icontains=machine)

        # Because MySQL db backend doesn't support DISTINCT ON syntax,
        # so manually filter duplicate machine names from the queryset
        temp_items = []
        machines = []
        for item in queryset:
            if item.machine not in machines:
                temp_items.append(item)
                machines.append(item.machine)

        data = {
            'list': machines,
        }
        return JsonResponse(data)

trends/templates/trends/trends-chart.html
{% extends 'estimator/base.html' %}
{% load bootstrap3 %}

{% block content %}
    <h1 class="mt-5">Machine Trend</h1>

    <form method="post" id="trend_form">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn-primary" id="go_button" type="submit">Show Chart</button>
    </form>
    <br>
    <div id="chartContainer" style="height: 500px; width: 100%;"></div>
{% endblock %}

{% block javascript %}
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    <script>
        // A $( document ).ready() block.
        $( document ).ready(function() {

            {# Machine charfield autocomplete function #}
            {# Source: https://stackoverflow.com/questions/5074329/django-jquery-and-autocomplete #}
            $("#id_machine").on('keyup', function(){
                var value = $(this).val();
                $.ajax({
                    url: "{% url 'trends:machine-autocomplete' %}",
                    data: {
                        'search': value
                    },
                    dataType: 'json',
                    success: function (data) {
                        {#console.log(data.list)#}
                        list = data.list;
                        $("#id_machine").autocomplete({
                            source: list,
                            minLength: 2,
                            messages: {
                                noResults : '',
                                results : function(resultsCount) {}
                            }
                        });
                    }
                });
            });

            {# Trend form submission handler #}
            $('#trend_form').submit(function (event) {
                event.preventDefault();

                trend_data = []
                maintenance_data = []
                min_yield_rate = 0
                max_yield_rate = 1

                var form = $(this).closest("form");
                $.ajax({
                    url: "{% url 'trends:get-machine-trends-and-maintenance' %}",
                    data: form.serialize(),
                    dataType: 'json',
                    success: function (response) {
                        data = jQuery.parseJSON(response)
                        {#console.log(response)#}

                        $.each(data, function (key, value) {
                            if (key == 'yield_rate') {
                                $.each(value, function (key, value) {

                                    // Source: https://jsfiddle.net/canvasjs/6ftyg155/
                                    trend_data.push({'label': value['period'], 'y': value['yield_rate']})
                                })
                            } else if (key == 'min_yield_rate') {
                                min_yield_rate = value
                            } else if (key == 'maintenance_history') {
                                $.each(value, function (key, value) {
                                    maintenance_data.push({'label': value['period'], 'y': value['occurrence']})
                                })
                            }
                        })

                        var machine = $('#id_machine').val()
                        renderChart(machine, trend_data, maintenance_data, min_yield_rate, max_yield_rate)

                    }, error: function() {
                        $('#chartContainer').hide()
                        alert("No data found! Please check your input parameters!")
                    }
                });
                return false;
            });


            {# Line chart rendering function #}
            function renderChart(machine, trend_data = [], maintenance_data = [], min_yield_rate) {
                var chart = new CanvasJS.Chart("chartContainer", {
                    animationEnabled: true,
                    exportFileName: "Machine Yield Rate and Maintenance Chart (" + machine + ")",  //Give any name accordingly
                    exportEnabled: true,
                    title: {
                        text: "Machine Yield Rate and Maintenance Chart (" + machine + ")",
                        fontSize: 28,
                        fontWeight: "normal",
                        wrap: true
                    },
                    dataPointWidth: 8,
                    dataPointMinWidth: 5,
                    dataPointMaxWidth: 10,
                    axisX: {
                        labelAutoFit: true,
                        labelWrap: true,
                        labelAngle: -80,
                        labelFontSize: 12,
                        labelFontWeight: "normal"
                    },
                    axisY: {
                        title: "Estimated Yield Rate",
                        titleFontSize: 20,
                        lineColor: "#C24642",
                        tickColor: "#C24642",
                        labelFontColor: "#C24642",
                        titleFontColor: "#C24642",
                        minimum:min_yield_rate,
                        maximum:1
                    },
                    axisY2: {
                        title: "Maintenance Occurrence",
                        titleFontSize: 20,
                        lineColor: "#2c96ee",
                        tickColor: "#2c96ee",
                        labelFontColor: "#2c96ee",
                        titleFontColor: "#2c96ee",
                        interval:1
                    },
                    toolTip: {
                        shared: true,
                        contentFormatter: function (e) {
                            var content = " ";
                            for (var i = 0; i < e.entries.length; i++) {
                                if (i == 0) {
                                    content += "Period: " + "<strong>" + e.entries[i].dataPoint.label + "</strong>";
                                    content += "<br/>";
                                }

                                content += e.entries[i].dataSeries.name + ": " + "<strong>" + e.entries[i].dataPoint.y + "</strong>";
                                content += "<br/>";
                            }
                            return content;
                        }
                    },
                    legend: {
                        cursor: "pointer",
                        itemclick: toggleDataSeries
                    },
                    data: [
                        {
                            type: "line",
                            name: "Yield Rate",
                            color: "#C24642",
                            axisYIndex: 0,
                            showInLegend: true,
                            dataPoints: trend_data
                        },
                        {
                            type: "column",
                            name: "Maintenance Occurrence",
                            color: "#2c96ee",
                            axisYType: "secondary",
                            showInLegend: true,
                            dataPoints: maintenance_data
                        }
                    ]
                })

                $('#chartContainer').show()
                chart.render();
            }

            function toggleDataSeries(e) {
                if (typeof (e.dataSeries.visible) === "undefined" || e.dataSeries.visible) {
                    e.dataSeries.visible = false;
                } else {
                    e.dataSeries.visible = true;
                }
                e.chart.render();
            }
        })
    </script>

    {{ form.media }}
{% endblock %}