estimator/urls.py
from django.conf import settings
from django.conf.urls import re_path
from django.conf.urls.static import static

from . import views

app_name = 'estimator'

urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name='index'),
    re_path(r'^home/$', views.HomeView.as_view(), name='home'),

    # File Upload Page URLs
    re_path(r'^file/list/$', views.FileList.as_view(), name='file-list'),
    re_path(r'^file/create/$', views.file_create, name='file-create'),
    re_path(r'^file/update/(?P<pk>\d+)/$', views.FileUpdate.as_view(), name='file-update'),
    re_path(r'^file/delete/(?P<pk>\d+)/$', views.FileDelete.as_view(), name='file-delete'),
    re_path(r'^file/analyze/(?P<pk>\d+)/$', views.analyze_data, name='file-analyze'),

    # Query Production Data Page URL
    re_path(r'^query-production-data/$', views.ProductionDataQuery.as_view(), name='query-production-data'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mces/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('estimator/', include('estimator.urls')),
    path('trends/', include('trends.urls')),
    path('report/', include('report.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

report/urls.py
from django.conf.urls import re_path

from . import views

app_name = 'report'

urlpatterns = [
    re_path(r'^download/$', views.ReportDownload.as_view(), name='download-page'),
    re_path(r'^download/report/$', views.download, name='download'),
]

trends/urls.py
from django.conf.urls import re_path

from . import views

app_name = 'trends'

urlpatterns = [
    re_path(r'^trend/$', views.TrendView.as_view(), name='yield-rate-maintenance-chart'),

    # AJAX URLs
    re_path(r'^ajax/get-machine-trends/$', views.get_machine_trends_and_maintenance,
            name='get-machine-trends-and-maintenance'),
    re_path(r'^ajax/machine-autocomplete/$', views.machine_autocomplete, name='machine-autocomplete'),
]

estimator/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.utils import timezone

import datetime

# Begin of PeiKai's code

# class HistoryMachineYieldRate(models.Model):
class Machine_Yield_Rate_History(models.Model):
    machine = models.TextField()
    period = models.TextField(null=True)
    start_period = models.DateField(default=timezone.now)
    end_period = models.DateField(default=timezone.now)
    yield_rate = models.FloatField()
    processed_pieces = models.TextField()
    analyze_type = models.TextField(default="Cell")

    class Meta:
        verbose_name = 'Machine Yield Rate History'
        verbose_name_plural = 'Machine Yield Rate Histories'
        ordering = ['yield_rate']

    def __str__(self):
        return str("(Week {0}) {1} , yield rate: {3}").format(self.period_in_week, self.machine, self.yield_rate)


class HistoryMachineUsage(models.Model):
      Lot = models.TextField()
      Period = models.TextField()
      Machine = models.TextField()

      class Meta:
          db_table = "HistoryMachineUsage"


class MachineUsedByLotInformation(models.Model):
    MaterialNumber = models.TextField()
    GBOM = models.TextField()
    Lot = models.CharField(max_length=255,db_index=True)
    FinishTime = models.TextField()
    TypeSettingNumber = models.TextField()
    Machine = models.CharField(max_length=255)
    CheckInTime = models.TextField()
    CheckOutTime = models.TextField()
    StationNumber = models.TextField()
    GoodPieces = models.TextField()
    BadPieces = models.TextField()
    FirstStation = models.TextField()
    CurrentTotalPieces = models.TextField()
    Period = models.CharField(max_length=255)

    class Meta:
        db_table = "MachineUsedByLotInformation"
        index_together = ["Period", "Machine"]
# End of PeiKai's code


class GBOM(models.Model):
    gbom = models.TextField(max_length=50, null=True)
    station = models.TextField(max_length=255, null=True)
    station_number = models.TextField(max_length=255, null=True)
    outsourcing = models.TextField(max_length=255, null=True)
    station_class = models.CharField(max_length=255, null=True)
    station_name = models.TextField(max_length=255, null=True)

    class Meta:
        verbose_name = 'GBOM'
        verbose_name_plural = 'GBOM'

    def __str__(self):
        return self.gbom


class LOT(models.Model):
    LOT = models.CharField(max_length=50)
    GBOM = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'LOT'
        verbose_name = 'LOT'


class Machine(models.Model):
    machine = models.CharField(max_length=6)
    type = models.CharField(max_length=10)
    GBOM = models.CharField(max_length=50)
    LOT = models.CharField(max_length=50)

    def __str__(self):
        return self.machine


# ALTER TABLE estimator_maintenance_history CONVERT TO CHARACTER SET big5 COLLATE big5_chinese_ci;
class Maintenance_History(models.Model):
    machine = models.TextField(max_length=6)
    serial_number = models.TextField(max_length=15, null=True)
    check_in_time = models.DateTimeField(default=timezone.now)
    check_out_time = models.DateTimeField(default=timezone.now)
    employee_id = models.TextField(max_length=5)
    operation_class = models.TextField(max_length=5)
    major_code = models.TextField(max_length=15)
    major_desc = models.TextField(max_length=255)
    minor_code = models.TextField(max_length=15)
    minor_desc = models.TextField(max_length=255)
    description = models.TextField(max_length=255)
    solution = models.TextField(max_length=255)
    reason = models.TextField(max_length=255)
    replace_parts = models.TextField(max_length=5)

    class Meta:
        ordering = ['check_in_time']
        verbose_name = 'Maintenance History'
        verbose_name_plural = 'Maintenance Histories'

    def __str__(self):
        return self.machine

class Employee(models.Model):
    employee_id = models.CharField(max_length=5)
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


# Uploaded file directory path
def user_directory_path(instance, filename):
    current_year = datetime.datetime.now().year
    start_period = instance.start_period.strftime('%Y%m%d').replace('-', '')
    end_period = instance.end_period.strftime('%Y%m%d').replace('-', '')

    if instance.type == 0:
        upload_path = 'uploads/Raw Production Data/By Check In Time/{0}/{1}_{2}.csv'.format(current_year, start_period, end_period)
    elif instance.type == 1:
        upload_path = 'uploads/Raw Production Data/By Warehouse Checking Date/{0}/{1}_{2}.csv'.format(current_year, start_period, end_period)
    elif instance.type == 2:
        upload_path = 'uploads/Machine Maintenance History/{0}/{1}_{2}.csv'.format(current_year, start_period, end_period)
    elif instance.type == 3:
        upload_path = 'uploads/Machine Bad Phenomenon Data/By Check In Time/{0}/{1}_{2}.csv'.format(current_year, start_period, end_period)
    elif instance.type == 4:
        upload_path = 'uploads/Machine Bad Phenomenon Data/By Warehouse Checking Date/{0}/{1}_{2}.csv'.format(current_year, start_period, end_period)
    elif instance.type == 5:
        upload_path = 'uploads/GBOM Data/{0}/{1}_{2}.csv'.format(current_year, start_period, end_period)
    else:
        upload_path = 'uploads/{0}/{1}_{2}.csv'.format(current_year, start_period, end_period)

    return upload_path

class File(models.Model):
    FILE_TYPE_CHOICES = (
        (0, 'Raw Production Data (by Check In Time)'),
        (1, 'Raw Production Data (by Warehouse Checking Date)'),
        (2, 'Machine Maintenance History'),
        (3, 'Machine Bad Phenomenon Data (by Check In Time)'),
        (4, 'Machine Bad Phenomenon Data (by Warehouse Checking Date)'),
        (5, 'GBOM Data'),
    )

    start_period = models.DateField(default=timezone.now)
    end_period = models.DateField(default=timezone.now)
    type = models.IntegerField(null=False, choices=FILE_TYPE_CHOICES, default=0)

    # Source : https://docs.djangoproject.com/en/2.1/ref/validators/#fileextensionvalidator
    file = models.FileField(upload_to=user_directory_path,
                            null=False,
                            validators=[FileExtensionValidator(["csv"])])
    last_modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["last_modified"]

    def __str__(self):
        return self.title

class Production_Data_By_Time(models.Model):
    part_number = models.TextField(max_length=255, null=True)
    check_in_time = models.DateTimeField(null=True)
    gbom = models.TextField(max_length=255, null=True)
    lot_number = models.TextField(max_length=255, null=True)
    station_number = models.TextField(max_length=255, null=True)
    station = models.TextField(max_length=255, null=True)
    station_name = models.TextField(max_length=255, null=True)
    machine_number = models.TextField(max_length=255, null=True)

    class Meta:
        ordering = ["check_in_time"]
        verbose_name = "Production Data By Time"
        verbose_name_plural = "Production Data By Time"

    def __str__(self):
        return self.part_number
#     Fill missing fields here...


class Production_Data_By_Warehouse(models.Model):
    part_number = models.TextField(max_length=255, null=True)
    check_in_time = models.DateTimeField(null=True)
    gbom = models.TextField(max_length=255, null=True)
    lot_number = models.TextField(max_length=255, null=True)
    station_number = models.TextField(max_length=255, null=True)
    station = models.TextField(max_length=255, null=True)
    station_name = models.TextField(max_length=255, null=True)
    machine_number = models.TextField(max_length=255, null=True)

    class Meta:
        verbose_name = "Production Data By Warehouse"
        verbose_name_plural = "Production Data By Warehouse"

    def __str__(self):
        return self.part_number


class Bad_Phenomenon_By_Time(models.Model):
    lot_number = models.TextField(max_length=255, null=True)
    check_in_time = models.TextField(max_length=255,null=True)
    defect_category = models.TextField(max_length=255, null=True)

    class Meta:
        ordering = ["check_in_time"]
        verbose_name = "Bad Phenomenon By Time"
        verbose_name_plural = "Bad Phenomena By Time"

    def __str__(self):
        return self.lot_name


class Bad_Phenomenon_By_Warehouse(models.Model):
    lot_number = models.TextField(max_length=255, null=True)
    check_in_time = models.TextField(max_length=255, null=True)
    defect_category = models.TextField(max_length=255, null=True)

    class Meta:
        verbose_name = "Bad Phenomenon By Warehouse"
        verbose_name_plural = "Bad Phenomena By Warehouse"

    def __str__(self):
        return self.lot_name

trends/models.py
from django.db import models

# Create your models here.

estimator/forms.py
from django import forms
from .models import *
from bootstrap_datepicker_plus import DatePickerInput


class FileForm(forms.ModelForm):
    start_period = forms.DateField(
        widget=DatePickerInput(format='%Y-%m-%d'),
        required=True
    )

    end_period = forms.DateField(
        widget=DatePickerInput(format='%Y-%m-%d'),
        required=True
    )

    file = forms.FileField(
        label='Select a File',
        help_text='Max. 15 MegaBytes'
    )

    class Meta:
        model = File
        fields = '__all__'

class ProductionDataQueryForm(forms.Form):
    QUERY_TYPE_CHOICES = (
        (0, 'GBOM'),
        (1, 'LOT')
    )

    input_type = forms.ChoiceField(
        label='Query based on:',
        choices=QUERY_TYPE_CHOICES,
        widget=forms.Select(),
        required=True
    )

    value = forms.CharField(
        widget=forms.TextInput(attrs={
            "class": "form-control"
        }),
        max_length=50,
    )

trends/views.py
from django.shortcuts import render
from django.views.generic import View
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.db.models import Min

from .forms import *

from estimator.models import Machine_Yield_Rate_History, Maintenance_History

import datetime
import json


class TrendView(View):
    def get(self, request):
        form = TrendForm()
        return render(request, 'trends/trends-chart.html', {'form': form})


@csrf_exempt
def get_machine_trends_and_maintenance(request):
    if request.is_ajax():
        # Get data sent using ajax
        start_date_str = request.GET.get('start_date', None)
        end_date_str = request.GET.get('end_date', None)
        machine = request.GET.get('machine', None)
        report_type = request.GET.get('report_type', None)

        # Convert str to datetime object
        date_format = '%Y-%m-%d'
        start_date = datetime.datetime.strptime(start_date_str, date_format)
        end_date = datetime.datetime.strptime(end_date_str, date_format)

        # Query yield rate based on the input parameters
        machine_yield_rates = Machine_Yield_Rate_History.objects \
            .values('period', 'yield_rate') \
            .filter(machine=machine, start_period__range=(start_date, end_date), end_period__range=(start_date, end_date), analyze_type=report_type) \
            .order_by('end_period')

        # Get min yield rate
        min_yield_rate = Machine_Yield_Rate_History.objects.values_list('yield_rate')\
            .filter(machine=machine,
                    start_period__range=(start_date, end_date),
                    end_period__range=(start_date, end_date),
                    analyze_type=report_type)\
            .aggregate(Min('yield_rate'))

        # Query maintenance data period based on the input parameters
        machine_maintenance = Maintenance_History.objects \
            .values('check_in_time') \
            .filter(machine=machine, check_in_time__range=(start_date, end_date)) \
            .order_by('check_in_time')

        # Split period into two (start and end period)
        period_date_dict = {}
        date_format = '%Y%m%d'
        for index, item in enumerate(machine_yield_rates):
            period = item['period'].split('_')
            period_date_dict[index] = {}
            period_date_dict[index]['start_period'] = datetime.datetime.strptime(period[0], date_format).date()
            period_date_dict[index]['end_period'] = datetime.datetime.strptime(period[1], date_format).date()

        # Calculate machine maintenance occurrences in between the start and end periods
        maintenance_occurrence_dict = {}
        occurrence_counter = 0
        loop_counter = 0
        for key, value in period_date_dict.items():
            for item in list(machine_maintenance):
                if item['check_in_time'].date() >= value['start_period'] and item['check_in_time'].date() <= value['end_period']:
                    occurrence_counter = occurrence_counter + 1
            maintenance_occurrence_dict[loop_counter] = {}
            maintenance_occurrence_dict[loop_counter]['period'] = value['start_period'].strftime(date_format) + "_" + \
                                                                  value['end_period'].strftime(date_format)
            maintenance_occurrence_dict[loop_counter]['occurrence'] = occurrence_counter
            occurrence_counter = 0
            loop_counter += loop_counter + 1

        # Parse all the results into json form
        result = json.dumps({
            'yield_rate': list(machine_yield_rates),
            'min_yield_rate': min_yield_rate['yield_rate__min'] - 0.01,
            'maintenance_history': maintenance_occurrence_dict,
        })

        return JsonResponse(result, content_type='application/json', safe=False)


@csrf_exempt
def machine_autocomplete(request):
    if request.is_ajax():
        machine = request.GET.get('search', None)
        queryset = Machine_Yield_Rate_History.objects.filter(machine__icontains=machine)

        # Because MySQL db backend doesn't support DISTINCT ON syntax,
        # so manually filter duplicate machine names from the queryset
        temp_items = []
        machines = []
        for item in queryset:
            if item.machine not in machines:
                temp_items.append(item)
                machines.append(item.machine)

        data = {
            'list': machines,
        }
        return JsonResponse(data)

estimator/templates/estimator/base.html
{% load static %}
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}Micro Crack Estimator System{% endblock %}</title>

    <link rel="icon" href="{% static 'estimator/icons/favicon.ico' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link href="{% static 'estimator/css/sticky-footer-navbar.css' %}" rel="stylesheet">

    {# jQuery autocomplete styling source: https://stackoverflow.com/questions/28285813/style-jquery-autocomplete-in-a-bootstrap-input-field #}
    <link href="{% static 'estimator/css/jquery-ui.css' %}" rel="stylesheet"/>
</head>

<body>

<header>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">Micro Crack Estimator System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'estimator:home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'estimator:file-list' %}">Estimator</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'report:download-page' %}">Report</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'trends:yield-rate-maintenance-chart' %}">Machine Trend</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

<!-- Begin page content -->
<main role="main" class="container">
    {% block content %}
    {% endblock %}
</main>

<footer class="footer">
    <div class="container">
        <span class="text-muted">Copyright © {% now 'Y' %} National Central University. All Rights Reserved</span>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{#<script src="https://code.jquery.com/jquery-1.12.4.js"></script>#}
<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30="
  crossorigin="anonymous"></script>
{#<script src="{% static 'estimator/js/jquery-ui.min.js' %}"></script>#}
<script src="{% static 'estimator/js/bootstrap.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

{% block javascript %}
{% endblock %}

</body>
</html>

estimator/templates/estimator/file-create.html
{% extends 'estimator/base.html' %}

{% load bootstrap3 %}

{% block title %}Upload File{% endblock %}

{% block content %}
    <h1 class="mt-5">Upload File</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {# Source: https://simpleisbetterthancomplex.com/tips/2016/09/06/django-tip-14-messages-framework.html #}
        {% include 'estimator/partials/messages.html' %}

        {% bootstrap_form form %}
        <input class="btn btn-primary" type="submit" value="Save" />
        <a href="{% url 'estimator:file-list' %}" class="btn btn-light" >Cancel</a>
    </form>
{% endblock %}

{% block javascript %}
    {{ form.media }}
{% endblock %}

estimator/templates/estimator/file-delete.html
{% extends 'estimator/base.html' %}

{% block title %}Delete File{% endblock %}

{% block content %}
    <h1 class="mt-5">Delete File</h1>

    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete this file?</p>
        <button class="btn btn-danger">Delete</button>
        <a href="{% url 'estimator:file-list' %}" class="btn btn-light" >Cancel</a>
    </form>
{% endblock %}

estimator/templates/estimator/file-list.html
{% extends 'estimator/base.html' %}

{% load static %}

{% block title %}File List{% endblock %}

{% block content %}
    <h1 class="mt-5">File List</h1>

    <a href="{% url 'estimator:file-create' %}" class="btn btn-primary float-right">Upload File</a>
    <br><br>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col" class="text-center">ID</th>
            <th scope="col" class="text-center">Start Period</th>
            <th scope="col" class="text-center">End Period</th>
            <th scope="col">File Type</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% if file_list %}
            {% for file in file_list %}
                <tr>
                    <th scope="row" class="text-center">{{ file.id }}</th>
                    <td scope="row" class="text-center">{{ file.start_period }}</td>
                    <td scope="row" class="text-center">{{ file.end_period }}</td>
                    <td scope="row">
                        {% if file.type == 0 %}
                            Production Data (by Check In Time)
                        {% elif file.type == 1 %}
                            Production Data (by Warehouse Checking Date)
                        {% elif file.type == 2 %}
                            Machine Maintenance History
                        {% elif file.type == 3 %}
                            Machine Bad Phenomenon Data (by Check In Time)
                        {% elif file.type == 4 %}
                            Machine Bad Phenomenon Data (by Warehouse Checking Date)
                        {% elif file.type == 5 %}
                            GBOM Data
                        {% endif %}
                    </td>
                    <td scope="row">
                        {# Let user analyze only production data type only #}
                        {% if file.type == 0 %}
                            <button id="button-{{ file.pk }}" data-href="{% url 'estimator:file-analyze' file.pk %}" class="btn btn-primary">
                                Analyze
                            </button>
                            <a href="{% url 'estimator:file-delete' file.pk %}" class="btn btn-danger">
                                Delete
                            </a>
                        {% elif file.type == 1 %}
                            <button id="button-{{ file.pk }}" data-href="{% url 'estimator:file-analyze' file.pk %}" class="btn btn-primary">
                                Analyze
                            </button>
                            <a href="{% url 'estimator:file-delete' file.pk %}" class="btn btn-danger">
                                Delete
                            </a>
                        {% else %}
                            <a href="{% url 'estimator:file-delete' file.pk %}" class="btn btn-danger">
                                Delete
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        {% endif %}
    </table>
    {% if is_paginated %}
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
              {% if page_obj.has_previous %}
                  <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
              {% else %}
                  <li class="page-item disabled"><a class="page-link" href="#"><span>Previous</span></a></li>
              {% endif %}
              {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                  <li class="page-item active"><a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a></li>
              {% else %}
                  <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
              {% endfor %}
              {% if page_obj.has_next %}
                  <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
              {% else %}
                  <li class="page-item disabled"><a class="page-link" href="#"><span>Next</span></a></li>
              {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endblock %}

{% block javascript %}
    <script src="{% static 'estimator/js/jquery.blockUI.js' %}"></script>
    <script>
        $( document ).ready(function() {

            // Source:
            // https://stackoverflow.com/questions/47342683/django-pass-a-list-items-id-pk-to-the-view-with-jquery-ajax
            $(".btn-primary").click(function(){
                $.blockUI({
                    message: '<p><img height="25" width="25" src="{% static 'estimator/gif/busy.gif' %}" /> Analysis in process</p><p><strong>Do not refresh or close the page while the page still running...</strong></p>'
                });

                var postData = {
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                }
                $.ajax({
                    type: "POST",
                    url: $(this).attr("data-href"),
                    data: postData,
                    success: function(response) {
                        $.unblockUI({
                            onUnblock: function(){ alert(response.message); }
                        });
                    },
                    error: function (error) {
                        $.unblockUI({
                            onUnblock: function(){ alert(error.responseJSON.error); }
                        });
                    }
                })
            });
        })
    </script>
{% endblock %}

estimator/templates/estimator/file-update.html
{% extends 'estimator/base.html' %}

{% load bootstrap3 %}

{% block title %}Update File{% endblock %}

{% block content %}
    <h1 class="mt-5">Update File</h1>

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn-primary" type="submit">Update</button>
        <a href="{% url 'estimator:file-list' %}" class="btn btn-light" >Cancel</a>
    </form>
{% endblock %}

estimator/templates/estimator/home.html
{% extends 'estimator/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1 class="mt-5">Home</h1>
{% endblock %}

estimator/templates/estimator/production-data-query.html
{% extends 'estimator/base.html' %}
{% load render_table from django_tables2 %}
{% load bootstrap3 %}

{% block content %}
    <h1 class="mt-5">Production Data Query</h1>

    <form method="post" id="prod-data-query-form">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn-primary" id="go_button" type="submit">Go</button>
        {% render_table table %}
    </form>
{% endblock %}